version: '3.4'

services:
    catalogdb:
        image: mongo
    basketdb:
        image: redis
    orderdb:
        image: mcr.microsoft.com/mssql/server
    rabbitmq:
        image: rabbitmq:3-management-alpine
    catalogapi:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
          context: .
          dockerfile: Src/Catalog/CatalogAPI/Dockerfile

    basketapi:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
          context: .
          dockerfile: Src/Basket/Basket.API/Dockerfile


    ordering.api:
        image: ${DOCKER_REGISTRY-}orderingapi
        build:
          context: .
          dockerfile: Src/Ordering/Ordering.API/Dockerfile